services:
  awesomeapp.api:
    build:
      args:
        port_http: 8080
        port_https: 8081
    ports:
      - "8080"
      - "8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
  awesomeapp.ui:
    build:
      args:
        host_network: "0.0.0.0"
        port: 3001
        api_url: "http://awesomeapp.api:8080"
        app_url: "http://localhost:3001"
    ports:
      - "3001:3001"
