version: '3.4'

services:
  awesomeapp.api:
    image: ${DOCKER_REGISTRY-}awesomeappapi
    build:
      context: ../AwesomeApp.API/
      dockerfile: AwesomeApp.API/Dockerfile
  awesomeapp.ui:
    image: ${DOCKER_REGISTRY-}awesomeappui
    build:
      context: ../AwesomeApp.UI/
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
