services:
  awesomeapp.api:
    image: ${DOCKER_REGISTRY-}awesomeappapi
    build:
      context: ../AwesomeApp.API/
      dockerfile: AwesomeApp.API/Dockerfile
  awesomeapp.ui:
    image: ${DOCKER_REGISTRY-}awesomeappui
    build:
      context: ../AwesomeApp.UI/
  nginx:
    image: ${DOCKER_REGISTRY-}nginx
    build:
      context: ../Nginx/
