export const PAGE_HOME = '/'
export const PAGE_FORBIDDEN = '/403'
export const PAGE_NOT_FOUND = '/404'
export const PAGE_ACCOUNT = '/account'
export const PAGE_ACCOUNT_EDIT = '/account/edit'
export const PAGE_CREATE_ACCOUNT = '/create-account'
export const PAGE_LOGIN = '/login'
